// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbLrrKB9MiREHmStSt1Y_1cPubNEez36k',
    appId: '1:246416052776:web:313cc181233df15a78db1d',
    messagingSenderId: '246416052776',
    projectId: 'elev-iq',
    authDomain: 'elev-iq.firebaseapp.com',
    storageBucket: 'elev-iq.firebasestorage.app',
    measurementId: 'G-W9RNELJB78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3BuA-F48HnF4RfeJ6tJdWcGOfzOawTks',
    appId: '1:246416052776:android:5f083efde5cbe16878db1d',
    messagingSenderId: '246416052776',
    projectId: 'elev-iq',
    storageBucket: 'elev-iq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh_zyk45qq79O8W5LnbWoXT5pAk_bIiVI',
    appId: '1:246416052776:ios:87f874fc80493d5978db1d',
    messagingSenderId: '246416052776',
    projectId: 'elev-iq',
    storageBucket: 'elev-iq.firebasestorage.app',
    iosClientId: '246416052776-mvskhdnh3pcu4u8n30h158adkv4as6ts.apps.googleusercontent.com',
    iosBundleId: 'com.eleviq.eleviqFlutter',
  );
}
